fix cursors overlay crash
BitPhinix/slate-yjs pull request #412
Opened 2023-07-09 13:16 UTC by ilya2204

Hello @BitPhinix I made a temporary solution that seems to fix cursor crashes and they work as they should. It is clear that this is not a targeted solution, but at the moment I think it's better than not being able to use them at all in react 18. #372

2023-07-15 20:27 UTC, BitPhinix commented
Merging this as a temporary fix! Would love for someone to dig into this further and fix a proper fix

2023-07-15 20:28 UTC, BitPhinix requested changes
Could you add a changeset?

2023-07-17 10:29 UTC, ilya2204 commented
@BitPhinix I added changeset. And I also had to add "try catch" in one more place, the original fix fixed repository example, but in my project with a more complex editor structure, cursors could still be broken

2023-07-17 17:42 UTC, BitPhinix approved these changes

2023-07-17 18:22 UTC, merged